//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hexa.Core.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hexa.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An object of type {0} was not available from the pool.
        /// </summary>
        internal static string AnObjectOfType0WasNotAvailableFromThePool
        {
            get
            {
                return ResourceManager.GetString("AnObjectOfType0WasNotAvailableFromThePool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can not directly save a child object.
        /// </summary>
        internal static string CanNotDirectlySaveAChildObject
        {
            get
            {
                return ResourceManager.GetString("CanNotDirectlySaveAChildObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificate file name format not valid. &apos;file|password&apos;.
        /// </summary>
        internal static string CertificateFileNameFormatNotValidFilePassword
        {
            get
            {
                return ResourceManager.GetString("CertificateFileNameFormatNotValidFilePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code: {0} was not present in data set collection.
        /// </summary>
        internal static string Code0WasNotPresentInDataSetCollection
        {
            get
            {
                return ResourceManager.GetString("Code0WasNotPresentInDataSetCollection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code Field Name not specified. Unable to Fetch by code..
        /// </summary>
        internal static string CodeFieldNameNotSpecifiedUnableToFetchByCode
        {
            get
            {
                return ResourceManager.GetString("CodeFieldNameNotSpecifiedUnableToFetchByCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not CreateType .
        /// </summary>
        internal static string CouldNotCreateType
        {
            get
            {
                return ResourceManager.GetString("CouldNotCreateType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not DefineType .
        /// </summary>
        internal static string CouldNotDefineType
        {
            get
            {
                return ResourceManager.GetString("CouldNotDefineType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not generate assembly: .
        /// </summary>
        internal static string CouldNotGenerateAssembly
        {
            get
            {
                return ResourceManager.GetString("CouldNotGenerateAssembly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not generate module builder.
        /// </summary>
        internal static string CouldNotGenerateModuleBuilder
        {
            get
            {
                return ResourceManager.GetString("CouldNotGenerateModuleBuilder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to creationTimeout cannot be negative.
        /// </summary>
        internal static string CreationTimeoutCannotBeNegative
        {
            get
            {
                return ResourceManager.GetString("CreationTimeoutCannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataLayerService can&apos;t be null..
        /// </summary>
        internal static string DataLayerServiceCanTBeNull
        {
            get
            {
                return ResourceManager.GetString("DataLayerServiceCanTBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Master Objects Can Not support ChildDelete Method.
        /// </summary>
        internal static string ErrorMasterObjectsCanNotSupportChildDeleteMethod
        {
            get
            {
                return ResourceManager.GetString("ErrorMasterObjectsCanNotSupportChildDeleteMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Reading Field: {0} form the Data Source..
        /// </summary>
        internal static string ErrorReadingField0FormTheDataSource
        {
            get
            {
                return ResourceManager.GetString("ErrorReadingField0FormTheDataSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identity can not be null..
        /// </summary>
        internal static string IdentityCanNotBeNull
        {
            get
            {
                return ResourceManager.GetString("IdentityCanNotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IEndpointBehaviorType specified in the FlatWsdlServiceBehaviorAttribute constructor must have a public empty constructor..
        /// </summary>
        internal static string IEndpointBehaviorTypeSpecifiedMustHaveAPublicEmptyConstructor
        {
            get
            {
                return ResourceManager.GetString("IEndpointBehaviorTypeSpecifiedMustHaveAPublicEmptyConstructor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid ConnectionStringId ({0}).
        /// </summary>
        internal static string InvalidConnectionStringId
        {
            get
            {
                return ResourceManager.GetString("InvalidConnectionStringId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string IsRequired
        {
            get
            {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LinqEntityAttribute not defined..
        /// </summary>
        internal static string LinqEntityAttributeNotDefined
        {
            get
            {
                return ResourceManager.GetString("LinqEntityAttributeNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to maxPoolSize cannot be negative.
        /// </summary>
        internal static string MaxPoolSizeCannotBeNegative
        {
            get
            {
                return ResourceManager.GetString("MaxPoolSizeCannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to minPoolSize cannot be greater than maxPoolSize.
        /// </summary>
        internal static string MinPoolSizeCannotBeGreaterThanMaxPoolSize
        {
            get
            {
                return ResourceManager.GetString("MinPoolSizeCannotBeGreaterThanMaxPoolSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to minPoolSize cannot be negative.
        /// </summary>
        internal static string MinPoolSizeCannotBeNegative
        {
            get
            {
                return ResourceManager.GetString("MinPoolSizeCannotBeNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater or equal than {1}.
        /// </summary>
        internal static string MustBeGreaterOrEqualThan1
        {
            get
            {
                return ResourceManager.GetString("MustBeGreaterOrEqualThan1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null..
        /// </summary>
        internal static string NameCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("NameCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object is not Child and can not be saved.
        /// </summary>
        internal static string ObjectIsNotChildAndCanNotBeSaved
        {
            get
            {
                return ResourceManager.GetString("ObjectIsNotChildAndCanNotBeSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object is not valid and can not be saved.
        /// </summary>
        internal static string ObjectIsNotValidAndCanNotBeSaved
        {
            get
            {
                return ResourceManager.GetString("ObjectIsNotValidAndCanNotBeSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object is still being edited and can not be saved.
        /// </summary>
        internal static string ObjectIsStillBeingEditedAndCanNotBeSaved
        {
            get
            {
                return ResourceManager.GetString("ObjectIsStillBeingEditedAndCanNotBeSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to page must be greater or equal to 1.
        /// </summary>
        internal static string PageMustBeGreaterOrEqualTo1
        {
            get
            {
                return ResourceManager.GetString("PageMustBeGreaterOrEqualTo1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type {0} cannot be unregistered because there are active threads waiting for an object..
        /// </summary>
        internal static string Type0CannotBeUnregisteredBecauseThereAreActiveThreadsWaitingForAnObject
        {
            get
            {
                return ResourceManager.GetString("Type0CannotBeUnregisteredBecauseThereAreActiveThreadsWaitingForAnObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not registered in the object pool..
        /// </summary>
        internal static string Type0IsNotRegisteredInTheObjectPool
        {
            get
            {
                return ResourceManager.GetString("Type0IsNotRegisteredInTheObjectPool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type cannot be null..
        /// </summary>
        internal static string TypeCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("TypeCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type {0} is already registered in the object pool.
        /// </summary>
        internal static string TypeIsAlreadyRegisteredInTheObjectPool
        {
            get
            {
                return ResourceManager.GetString("TypeIsAlreadyRegisteredInTheObjectPool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to read key or iv..
        /// </summary>
        internal static string UnableToReadKeyOrIv
        {
            get
            {
                return ResourceManager.GetString("UnableToReadKeyOrIv", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to start provider.
        /// </summary>
        internal static string UnableToStartProvider
        {
            get
            {
                return ResourceManager.GetString("UnableToStartProvider", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} value is not an email.
        /// </summary>
        internal static string ValueIsNotAnEmail
        {
            get
            {
                return ResourceManager.GetString("ValueIsNotAnEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} value is not correctly formatted.
        /// </summary>
        internal static string ValueIsNotCorrectlyFormatted
        {
            get
            {
                return ResourceManager.GetString("ValueIsNotCorrectlyFormatted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} value is not of the correct type.
        /// </summary>
        internal static string ValueIsNotOfTheCorrectType
        {
            get
            {
                return ResourceManager.GetString("ValueIsNotOfTheCorrectType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} value must be between {1} and {2}.
        /// </summary>
        internal static string ValueMustBeBetween1And2
        {
            get
            {
                return ResourceManager.GetString("ValueMustBeBetween1And2", resourceCulture);
            }
        }
    }
}
